### ISSUE TITLE
Error on example

### ISSUE THREAD

**Issue by exdeniz** [contentful-labs/cf-graphql#31]
I try example with my space and tokens
```
node server.js
Space ID, CDA token and CMA token provided
Fetching space (idgst6210pol) content types to create a space graph
{ Error: Unauthorized
    at checkStatus (/Users/exdeniz/Project/ecuresearch/site/node_modules/cf-graphql/src/http-client.js:59:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  response:
   Body {
     url: 'https://api.contentful.com/spaces/idgst6210pol/content_types?limit=1000',
     status: 401,
     statusText: 'Unauthorized',
     headers: Headers { _headers: [Object] },
     ok: false,
     body:
      Gunzip {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object],
        bytesRead: 0,
        _opts: {},
        _chunkSize: 16384,
        _flushFlag: 0,
        _finishFlushFlag: 4,
        _handle: [Object],
        _hadError: false,
        _buffer: <Buffer 7b 0a 20 20 22 73 79 73 22 3a 20 7b 0a 20 20 20 20 22 74 79 70 65 22 3a 20 22 45 72 72 6f 72 22 2c 0a 20 20 20 20 22 69 64 22 3a 20 22 41 63 63 65 73 ... >,
        _offset: 0,
        _level: -1,
        _strategy: 0 },
     bodyUsed: false,
     size: 0,
     timeout: 0,
     _raw: [],
     _abort: false } }
```

**Comment by exdeniz** [comment]
Not right token for CMA, sorry
