### ISSUE TITLE
GraphQL error: Unprocessable Entity

### ISSUE THREAD

**Issue by creaux** [contentful-labs/cf-graphql#35]
When I'm calling graphql from the same server in **nodejs** I'm getting this issue. When I'm calling same endpoint from browser it works well. :scream:

```
Error: GraphQL error: Unprocessable Entity
    at ApolloError.Error (native)
    at new ApolloError (/Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/errors/ApolloError.js:34:28)
    at /Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/core/QueryManager.js:325:41
    at /Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/core/QueryManager.js:818:25
    at Array.forEach (native)
    at /Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/core/QueryManager.js:815:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (/Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/core/QueryManager.js:812:42)
    at /Users/username/Development/javascript/redux/project/node_modules/apollo-client/src/core/QueryManager.js:747:31
    at process._tickCallback (internal/process/next_tick.js:103:7)
  graphQLErrors: 
   [ { message: 'Unprocessable Entity',
       locations: [Object],
       stack: 'Error: Unprocessable Entity\n    at checkStatus (/Users/username/Development/javascript/redux/project/node_modules/cf-graphql/src/http-client.js:59:17)\n    at process._tickCallback (internal/process/next_tick.js:103:7)',
       path: [Object] } ],
  networkError: null,
  message: 'GraphQL error: Unprocessable Entity',
  extraInfo: undefined,
  queryErrors: [ [Circular] ] }
```
Is anyone else running `cf-graphql` in nodejs?

**Comment by creaux** [comment]
I suggest in this case to track http request over network as graphql server running in nodejs you have to stick into there.
