### ISSUE TITLE
Question on npm start

### ISSUE THREAD

**Issue by DaveLindberg** [contentful-labs/cf-graphql#44]
I receive an error using `npm start`. 
```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dlindberg/.npm/_logs/2017-12-27T02_40_47_621Z-debug.log
```

Here's the log contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v6.11.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:348:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:457:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
5 verbose cwd /Users/dlindberg/Code/cf-graphql
6 verbose Darwin 17.3.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v6.11.4
9 verbose npm  v5.6.0
10 error missing script: start
11 verbose exit [ 1, true ]
```
i'm missing either the start.js file, or something else entirely...

**Comment by digigarlab** [comment]
There is no script `start` in [the package.json of this repo](https://github.com/contentful-labs/cf-graphql/blob/master/package.json#L42)

From your logs it looks like you are trying to run start from `/Users/dlindberg/Code/cf-graphql` but what you probably want is to run it from `/Users/dlindberg/Code/cf-graphql/demo`.

**Comment by DaveLindberg** [comment]
thanks!
