### ISSUE TITLE
Schema must be an instance of GraphQLSchema

### ISSUE THREAD

**Issue by braidn** [contentful-labs/cf-graphql#45]
Getting the above error when setting up the demo and accessing GraphiQL after running `server.js`. I currently have tried this with two different spaces. One with a bunch of custom objects, the other with a brand new, blog space (default from Contentful).

The full error coming from the GraphiQL route is after activating detailed errors:

```
  "message": "Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.",
      "stack": "Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.\n    at invariant (/Users/braidn/src/middleman-itgc/node_modules/graphql/jsutils/invariant.js:19:11)\n    at validate (/Users/braidn/src/middleman-itgc/node_modules/graphql/validation/validate.js:60:72)\n    at /Users/braidn/src/middleman-itgc/node_modules/express-graphql/dist/index.js:138:52\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
```

I have attempted to pull the code from here:

https://github.com/contentful-labs/cf-graphql/blob/master/src/schema.js#L25

Into the server.js and make sure that the schema passed to the server in the demo is in fact an instance of GraphQLSchema. No matter how many functions are pulled into the server.js from the schema file, the app seems to continually fail to produce an instance of GraphQLSchema.

Thanks again for the help and if there is any other troubleshooting I can do, feel free to reach out.

**Comment by jwicks** [comment]
This comment and thread helped me resolve the issue: https://github.com/graphql/graphiql/issues/58#issuecomment-226258017

**Comment by braidn** [comment]
Interesting @jwicks ! So this is purely a weird a weird NPM bug. Will check it out and close or update. Thank you again.

**Comment by rtm619** [comment]
I faced the same issue and this might help. Try installing these specific packages:

"cf-graphql": "^0.5.0",
    "contentful": "^7.0.5",
    "cors": "^2.8.4",
    "express": "^4.16.4",
    "express-graphql": "^0.6.7",
